app/urls.py
from django.urls import path
from .import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),

    path('login/', views.iniciar_sesion_view, name='iniciar_sesion_view'),
    path('post_login/', views.iniciar_sesion_post, name='iniciar_sesion_post'),
    path('registro/', views.form_registro_view, name='form_registro_view'),
    path('registro_post/', views.registro_post, name='registro_post'),

    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),

    # Lista de categorias
    path('categorias/', views.categorias_view, name='categorias'),
    # # Una categoria
    path('categorias/<int:id>', views.categoria_view, name='categoria'),
    # Formulario para crear categoría
    path('categorias/crear', views.form_crear_categoria_view,
         name="form_crear_categoria_view"),
    path('categorias/crear_post', views.crear_categoria_post,
         name="crear_categoria_post"),

    path('peliculas/', views.peliculas_view, name='peliculas'),
    # Formulario para crear película
    path('peliculas/crear', views.form_crear_pelicula_view,
         name="form_crear_pelicula_view"),
    path('peliculas/crear_post', views.crear_pelicula_post,
         name="crear_pelicula_post"),


    path('acerca/', views.acerca_view, name="acerca")
]

blockbuster_nube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(max_length=200, null=False)
    descripcion = models.TextField(null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        app_label: 'app'


class Pelicula(models.Model):
    titulo = models.CharField(max_length=200, null=False)
    year = models.IntegerField(null=True)
    sinopsis = models.TextField(null=True)
    categoria = models.ForeignKey(
        Categoria,
        related_name='peliculas',
        null=False,
        on_delete=models.PROTECT
    )
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

    class Meta:
        app_label: 'app'

app/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from .models import Categoria, Pelicula
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'app/home.html')


def form_registro_view(request):
    return render(request, 'app/registro.html')


def registro_post(request):
    # Obtiene los datos de registro
    nombres = request.POST['nombres']
    apellidos = request.POST['apellidos']
    username = request.POST['username']
    password = request.POST['password']

    # Crea un usuario
    usuario = User()
    usuario.first_name = nombres
    usuario.last_name = apellidos
    usuario.username = username
    usuario.set_password(password)

    print(usuario)
    # Guarda el usuario en la BD
    usuario.save()

    # Redireccionar a login
    return redirect('app:iniciar_sesion_view')


def iniciar_sesion_view(request):
    return render(request, 'app/login.html')


def iniciar_sesion_post(request):
    # Obtiene los datos de autenticación
    u = request.POST['username']
    p = request.POST['password']

    # Obtiene el usuario con username y password
    usuario = authenticate(username=u, password=p)

    if usuario is None:
        return render(request, 'app/errorLogin.html')
    else:
        # Inicia sesión
        login(request, usuario)
        return redirect('app:index')


def cerrar_sesion(request):
    # Cierra la sesión activa
    logout(request)
    return redirect('app:index')


@login_required
def categorias_view(request):
    # Obtiene todas las categorias
    lista = Categoria.objects.all()
    # Crea el contexto
    contexto = {
        'categorias': lista
    }

    return render(request, 'app/categorias.html', contexto)


@login_required
def categoria_view(request, id):
    # Crea el contexto
    contexto = {
        'actor': 'Tom Hanks',
        'edad': 64,
        'esJubilado': False,
        'filmografia': [
            {'titulo': 'Cast Away', 'year': 2000},
            {'titulo': 'Forrest Gump', 'year': 1994},
            {'titulo': 'DaVinci Code', 'year': 2006},
            {'titulo': 'Toy Story', 'year': 1995}
        ]
    }

    return render(request, 'app/categoria.html', contexto)


@login_required
def form_crear_categoria_view(request):
    return render(request, 'app/crearCategoria.html')


@login_required
def crear_categoria_post(request):
    # Obtiene los datos de la categoria
    nombre = request.POST['nombre']
    descripcion = request.POST['descripcion']

    # Crea el objeto Categoria
    c = Categoria()
    c.nombre = nombre
    c.descripcion = descripcion

    # Guarda la categoria en BD
    c.save()

    return redirect('app:categorias')


@login_required
def form_crear_pelicula_view(request):
    # Obtiene las categorias
    lista_categorias = Categoria.objects.all().order_by('nombre')

    # Crea el contexto
    contexto = {
        'categorias': lista_categorias
    }

    return render(request, 'app/crearPelicula.html', contexto)


@login_required
def crear_pelicula_post(request):
    # Obtiene los datos del formulario
    titulo = request.POST['titulo']
    year = int(request.POST['year'])
    sinopsis = request.POST['sinopsis']
    id_categoria = int(request.POST['categoria'])

    # Obtiene la categoria
    categoria = Categoria.objects.get(id=id_categoria)

    # Crea la pelicula
    p = Pelicula()
    p.titulo = titulo
    p.year = year
    p.sinopsis = sinopsis
    p.categoria = categoria

    # Guarda la pelicula en la BD
    p.save()

    return redirect('app:peliculas')


@login_required
def peliculas_view(request):
    # Obtiene las peliculas
    lista_peliculas = Pelicula.objects.order_by('titulo')

    contexto = {
        'peliculas': lista_peliculas
    }

    return render(request, 'app/peliculas.html', contexto)


def acerca_view(request):
    return render(request, 'app/acerca.html')

app/templates/app/acerca.html
{% extends 'app/base.html' %}

{% block titulo %}
Acerca de
{% endblock%}

{% block contenido %}
<h1>Ingenieros</h1>
<ul>
    <li>Steve Jobs</li>
    <li>Steve Wozniak</li>
</ul>
{% endblock %}

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorias</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'app/estilo.css' %}">
</head>

<body>

    <div class="contenedor">
        <header>
            <div class="logo">
                BLOCKBUSTER
            </div>
            <div class="titulo">
                <i class="fas fa-angle-double-right"></i> {% block titulo %}TITULO{% endblock %}
            </div>
        </header>
        <nav>
            <ul>
                <li><a href="{% url 'app:peliculas' %}">Peliculas</a>
                <li><a href="{% url 'app:categorias' %}">Categorias</a></li>
                <li><a href="{% url 'app:acerca' %}">Acerca</a></li>
                <li><a href="#">Salir</a></li>
            </ul>
        </nav>
        <main>
            {% block contenido %}
            {% endblock %}
        </main>
    </div>

</body>

</html>

app/templates/app/categoria.html
{% extends 'app/base.html' %}

{% block titulo %}
Categoria
{% endblock %}

{% block contenido %}
<a href="{% url 'app:peliculas' %}">Ir a la pagina de peliculas</a>
<br>
<a href="{% url 'app:index' %}">Ir al inicio</a>
<h1>Categoria</h1>
<p>El nombre del actor es {{ actor }} y tiene {{ edad }} años.</p>
{% if esJubilado %}
<p>El actor es jubilado</p>
{% else %}
<p>El actor aún trabaja activamente en la industria del cine y la TV</p>
{% endif %}
<h2>Filmografía del actor</h2>

<ul>
    {% for pelicula in filmografia %}
    <li>{{ pelicula.titulo }}</li>
    {% endfor %}
</ul>
<hr>
<h2>Tabla de peliculas de actor</h2>

<table border="1">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Año</th>
        </tr>
    </thead>
    <tbody>
        {% for movie in filmografia %}
        <tr>
            <td>{{ movie.titulo }}</td>
            <td>
                {{ movie.year }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app/templates/app/categorias.html
{% extends "app/base.html" %}

{% block titulo %}
Categorias
{% endblock %}

{% block contenido %}
<a href="{% url 'app:form_crear_categoria_view' %}">Crear categoría</a>

<ul>
    {% for c in categorias %}
    <li>{{ c.nombre }}</li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/app/crearCategoria.html
{% extends "app/base.html" %}

{% block titulo %}
Crear categoria
{% endblock %}

{% block contenido %}
<h3>Datos de la categoría</h3>
<hr>
<form action="{% url 'app:crear_categoria_post' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <label>Nombre</label>
        <input type="text" name="nombre">
    </fieldset>
    <fieldset>
        <label>Descripción</label>
        <input type="text" name="descripcion">
    </fieldset>
    <fieldset>
        <button type="submit">Crear categoría</button>
    </fieldset>
</form>

{% endblock %}

app/templates/app/crearPelicula.html
{% extends 'app/base.html' %}

{% block titulo %}
Crear película
{% endblock %}

{% block contenido %}
<h3>Datos de la película</h3>
<hr>
<form action="{% url 'app:crear_pelicula_post' %}" method="POST">
    {% csrf_token %}
    <fieldset>
        <label>Titulo</label>
        <input type="text" name="titulo">
    </fieldset>
    <fieldset>
        <label>Año</label>
        <input type="number" name="year">
    </fieldset>
    <fieldset>
        <label>Sinopsis</label>
        <textarea name="sinopsis" cols="30" rows="5"></textarea>
    </fieldset>
    <fieldset>
        <label>Categoria</label>
        <select name="categoria">
            {% for c in categorias %}
            <option value="{{c.id}}">{{c.nombre}}</option>
            {% endfor %}
        </select>
    </fieldset>
    <fieldset>
        <button type="submit">Crear pelicula</button>
    </fieldset>
</form>
{% endblock %}

app/templates/app/errorLogin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error de inicio de sesión</title>
</head>

<body>

    <h1>Error en los datos</h1>
    <a href="{% url 'app:iniciar_sesion_view' %}">Ingresar</a>

</body>

</html>

app/templates/app/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blockbuster</title>
</head>

<body>

    <h1>Bienvenido a Blockbuster</h1>
    {% if request.user.is_authenticated %}
    <span>Bienvenido {{ request.user.first_name }}</span>
    <br>
    <a href="{% url 'app:cerrar_sesion' %}">cerrar sesión</a>
    {% else %}
    <a href="{% url 'app:iniciar_sesion_view' %}">iniciar sesión</a>
    <br>
    <a href="{% url 'app:form_registro_view' %}">Crear cuenta</a>
    {% endif %}

</body>

</html>

app/templates/app/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingresar</title>
    <style>
        body {
            display: grid;
            place-items: center;
        }

        fieldset {
            border: 0;
            outline: none;
        }
    </style>
</head>

<body>
    <form action="{% url 'app:iniciar_sesion_post' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <label>Username</label>
            <input type="text" name="username">
        </fieldset>
        <fieldset>
            <label>Password</label>
            <input type="password" name="password">
        </fieldset>
        <fieldset>
            <button type="submit">Iniciar sesión</button>
        </fieldset>
    </form>
</body>

</html>

app/templates/app/peliculas.html
{% extends 'app/base.html' %}

{% block titulo %}
Peliculas
{% endblock %}

{% block contenido %}

<a href="{% url 'app:form_crear_pelicula_view' %}">Crear pelicula</a>

<table border="1">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Año</th>
            <th>Categorias</th>
        </tr>
    </thead>
    <tbody>
        {% for p in peliculas %}
        <tr>
            <td>{{ p.titulo }}</td>
            <td>
                {% if p.year %}
                {{ p.year }}
                {% else %}
                Año no disponible
                {% endif %}
            </td>
            <td>{{ p.categoria }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app/templates/app/registro.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <style>
        body {
            display: grid;
            place-items: center;
        }

        fieldset {
            border: 0;
            outline: none;
        }
    </style>
</head>

<body>

    <h1>Ingreso a Blockbuster</h1>
    <form action="{% url 'app:registro_post' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <label>Nombres</label>
            <input type="text" name="nombres">
        </fieldset>
        <fieldset>
            <label>Apellidos</label>
            <input type="text" name="apellidos">
        </fieldset>
        <fieldset>
            <label>Username</label>
            <input type="text" name="username">
        </fieldset>
        <fieldset>
            <label>Password</label>
            <input type="password" name="password">
        </fieldset>
        <fieldset>
            <button type="submit">Crear cuenta</button>
        </fieldset>
    </form>

</body>

</html>